### PR TITLE
Matching UI

### LINKED ISSUE #45: Basic UI - Interviews page to find peers who are interested in working with you

### PR DESCRIPTION
**Pull request by ckcherry23**
Fixes #45

### CODE REVIEW

**Comment by chunweii** [comment]
Since the match backend is completed, should we integrate the match frontend in this PR too?

**Comment by ong6** [comment]
> Since the match backend is completed, should we integrate the match frontend in this PR too?

we can do it in a new PR

**Review by ong6 — APPROVED** [review]
LGTM, after the match is found we redirect them to the Room right?

**Comment by ckcherry23** [comment]
> LGTM, after the match is found we redirect them to the Room right? 

Right now they should accept the match and then they are redirected

If this is not possible with the backend implementation, I can redirect automatically

**Comment by ong6** [comment]
> > LGTM, after the match is found we redirect them to the Room right?
> 
> Right now they should accept the match and then they are redirected
> 
> If this is not possible with the backend implementation, I can redirect automatically

It should be fine - matching service should give a room ID we can redirect to

**Pull request merged**
